<?xml version='1.0' encoding='utf-8'?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<packaging>pom</packaging>

	<groupId>cn.hutool-plus</groupId>
	<artifactId>hutool-parent</artifactId>
	<version>5.8.29</version>
	<name>hutool</name>
	<description>Hutool-Plus是一个小而全的Java工具类库，通过静态方法封装，降低相关API的学习成本，提高工作效率，使Java拥有函数式语言般的优雅，让Java语言也可以“甜甜的”。</description>
	<url>https://gitee.com/ssoss/hutool-plus</url>

	<modules>
		<module>hutool-plus-all</module>
		<module>hutool-plus-bom</module>
		<module>hutool-plus-aop</module>
		<module>hutool-plus-bloomFilter</module>
		<module>hutool-plus-cache</module>
		<module>hutool-plus-core</module>
		<module>hutool-plus-cron</module>
		<module>hutool-plus-crypto</module>
		<module>hutool-plus-db</module>
		<module>hutool-plus-dfa</module>
		<module>hutool-plus-extra</module>
		<module>hutool-plus-http</module>
		<module>hutool-plus-log</module>
		<module>hutool-plus-script</module>
		<module>hutool-plus-setting</module>
		<module>hutool-plus-system</module>
		<module>hutool-plus-json</module>
		<module>hutool-plus-poi</module>
		<module>hutool-plus-captcha</module>
		<module>hutool-plus-socket</module>
		<module>hutool-plus-jwt</module>
	</modules>

	<properties>
		<project.build.sourceEncoding>utf-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>utf-8</project.reporting.outputEncoding>

		<Automatic-Module-Name>cn.hutool-plus</Automatic-Module-Name>

		<!-- versions -->
		<compile.version>8</compile.version>
		<junit.version>5.10.2</junit.version>
		<lombok.version>1.18.30</lombok.version>
	</properties>

	<dependencies>
		<!-- 全局单元测试 -->
		<dependency>
			<groupId>org.junit.vintage</groupId>
			<artifactId>junit-vintage-engine</artifactId>
			<version>${junit.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>${lombok.version}</version>
			<scope>test</scope>
		</dependency>
	</dependencies>


	<developers>
		<developer>
			<id>ssoss</id>
			<name>lingengkeng</name>
			<email>lingengkeng007@163.com</email>
			<roles>
				<role>Project Manager</role>
				<role>Architect</role>
			</roles>
		</developer>
	</developers>

	<scm>
		<connection>https://gitee.com/ssoss/hutool-plus.git</connection>
		<developerConnection>scm:git:ssh://git@gitee.com:ssoss/hutool-plus.git</developerConnection>
		<url>https://gitee.com/ssoss/hutool-plus.git</url>
	</scm>

	<!--	<issueManagement>-->
	<!--		<system>Github Issue</system>-->
	<!--		<url>https://github.com/dromara/hutool/issues</url>-->
	<!--	</issueManagement>-->

	<licenses>
		<license>
			<name>Mulan Permissive Software License，Version 2</name>
			<url>https://license.coscl.org.cn/MulanPSL2</url>
		</license>
	</licenses>

	<!--	<scm>-->
	<!--		<connection>scm:git@github.com:dromara/hutool.git</connection>-->
	<!--		<developerConnection>scm:git@github.com:dromara/hutool.git</developerConnection>-->
	<!--		<url>git@github.com:dromara/hutool.git</url>-->
	<!--	</scm>-->

	<build>
		<plugins>

			<!--   central发布插件    -->
			<plugin>
				<groupId>org.sonatype.central</groupId>
				<artifactId>central-publishing-maven-plugin</artifactId>
				<version>0.4.0</version>
				<extensions>true</extensions>
				<configuration>
					<publishingServerId>ssoss</publishingServerId>
					<tokenAuth>true</tokenAuth>
				</configuration>
			</plugin>
			<!--   source源码插件 -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<version>2.2.1</version>
				<executions>
					<execution>
						<id>attach-sources</id>
						<goals>
							<goal>jar-no-fork</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<!--   javadoc插件 -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<version>2.9.1</version>
				<executions>
					<execution>
						<id>attach-javadocs</id>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-gpg-plugin</artifactId>
				<version>1.5</version>
				<configuration>
					<executable>D:\SOFTWARE\GnuPG\bin\gpg.exe</executable>
					<keyname>ssoss</keyname>
				</configuration>
				<executions>
					<execution>
						<id>sign-artifacts</id>
						<phase>verify</phase>
						<goals>
							<goal>sign</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

		</plugins>
	</build>


	<profiles>
		<profile>
			<id>release</id>
			<distributionManagement>
				<snapshotRepository>
					<id>oss</id>
					<url>https://oss.sonatype.org/content/repositories/snapshots/</url>
				</snapshotRepository>
				<repository>
					<id>oss</id>
					<url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
				</repository>
			</distributionManagement>
			<build>
				<plugins>
					<!-- Source -->
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-source-plugin</artifactId>
						<version>3.2.1</version>
						<executions>
							<execution>
								<id>oss</id>
								<phase>package</phase>
								<goals>
									<goal>jar-no-fork</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
					<!-- 测试覆盖度 -->
					<plugin>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>cobertura-maven-plugin</artifactId>
						<version>2.7</version>
						<configuration>
							<formats>
								<format>html</format>
								<format>xml</format>
							</formats>
							<check/>
						</configuration>
					</plugin>
					<!-- Gpg Signature -->
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-gpg-plugin</artifactId>
						<version>1.6</version>
						<executions>
							<execution>
								<id>oss</id>
								<phase>verify</phase>
								<goals>
									<goal>sign</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.sonatype.plugins</groupId>
						<artifactId>nexus-staging-maven-plugin</artifactId>
						<version>1.6.8</version>
						<extensions>true</extensions>
						<configuration>
							<serverId>oss</serverId>
							<nexusUrl>https://oss.sonatype.org/</nexusUrl>
							<autoReleaseAfterClose>true</autoReleaseAfterClose>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>

</project>
